[project]
name = "safedreamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "absl-py==2.3.0",
    "annotated-types==0.7.0",
    "astunparse==1.6.3",
    "certifi==2025.4.26",
    "charset-normalizer==3.4.2",
    "chex>=0.1.90",
    "click==8.1.8",
    "cloudpickle==3.1.1",
    "contourpy==1.3.0",
    "cycler==0.12.1",
    "decorator==5.2.1",
    "dm-tree==0.1.8",
    "einops==0.8.1",
    "etils==1.5.2",
    "eval-type-backport==0.2.2",
    "farama-notifications==0.0.4",
    "flatbuffers==25.2.10",
    "fonttools==4.58.2",
    "gast==0.6.0",
    "gitdb==4.0.12",
    "gitpython==3.1.44",
    "glfw==2.9.0",
    "google-pasta==0.2.0",
    "grpcio==1.73.0",
    "gymnasium==0.29.0",
    "gymnasium-robotics>=1.2.2",
    "h5py==3.14.0",
    "idna==3.10",
    "imageio==2.37.0",
    "imageio-ffmpeg==0.6.0",
    "importlib-metadata==8.7.0",
    "importlib-resources==6.5.2",
    "jax[cuda12]==0.4.30",
    "jinja2==3.1.6",
    "keras==3.10.0",
    "kiwisolver==1.4.7",
    "libclang==18.1.1",
    "markdown==3.8",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "matplotlib==3.9.4",
    "mdurl==0.1.2",
    "ml-dtypes==0.5.1",
    "moviepy==2.2.1",
    "mujoco==2.3.3",
    "namex==0.1.0",
    "numpy>=2.1.3",
    "nvidia-cublas-cu12==12.5.3.2",
    "nvidia-cuda-cupti-cu12==12.5.82",
    "nvidia-cuda-nvcc-cu12==12.5.82",
    "nvidia-cuda-nvrtc-cu12==12.5.82",
    "nvidia-cuda-runtime-cu12==12.5.82",
    "nvidia-cudnn-cu12==9.3.0.75",
    "nvidia-cufft-cu12==11.2.3.61",
    "nvidia-curand-cu12==10.3.6.82",
    "nvidia-cusolver-cu12==11.6.3.83",
    "nvidia-cusparse-cu12==12.5.1.3",
    "nvidia-nccl-cu12==2.23.4",
    "nvidia-nvjitlink-cu12==12.5.82",
    "opencv-python==4.11.0.86",
    "opt-einsum==3.4.0",
    "optax==0.2.4",
    "optree==0.16.0",
    "packaging==25.0",
    "pandas==2.3.1",
    "pettingzoo==1.24.3",
    "pillow==11.2.1",
    "platformdirs==4.3.8",
    "proglog==0.1.12",
    "protobuf==5.29.5",
    "psutil==7.0.0",
    "pydantic==2.11.5",
    "pydantic-core==2.33.2",
    "pygame==2.1.0",
    "pygments==2.19.1",
    "pyopengl==3.1.9",
    "pyparsing==3.2.3",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.1.0",
    "pytz==2025.2",
    "pyyaml==6.0.2",
    "requests==2.32.4",
    "rich==14.0.0",
    "ruamel-yaml==0.17.21",
    "ruamel-yaml-clib==0.2.12",
    "safety-gymnasium",
    "scipy==1.13.1",
    "seaborn==0.13.2",
    "sentry-sdk==2.29.1",
    "setproctitle==1.3.6",
    "six==1.17.0",
    "smmap==5.0.2",
    "tensorboard==2.19.0",
    "tensorboard-data-server==0.7.2",
    "tensorflow==2.19.0",
    "tensorflow-io-gcs-filesystem==0.37.1",
    "tensorflow-probability==0.25.0",
    "termcolor==3.1.0",
    "toolz==1.0.0",
    "tqdm==4.67.1",
    "typing-extensions==4.14.0",
    "typing-inspection==0.4.1",
    "tzdata==2025.2",
    "urllib3==2.4.0",
    "wandb==0.20.1",
    "werkzeug==3.1.3",
    "wrapt==1.17.2",
    "xmltodict==0.14.2",
    "zipp==3.23.0",
]

[tool.uv]
environments = ["sys_platform == 'linux'"]  # stop uv from solving darwin/aarch64 splits you don't want
find-links = ["https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"]

[tool.uv.workspace]
members = [
    "safety-gymnasium",
]

[tool.uv.sources]
safety-gymnasium = { workspace = true }
