name: hrssm_saferl
channels:
  - nvidia/label/cuda-12.8.0
  - anaconda
  - defaults
dependencies:
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - ansi2html==1.9.1
      - antlr4-python3-runtime==4.8
      - appdirs==1.4.4
      - atari-py==0.2.9
      - attrs==23.1.0
      - blinker==1.7.0
      - captum==0.7.0
      - certifi==2023.11.17
      - cffi==1.16.0
      - cloudpickle==3.1.1
      - comm==0.2.0
      - configargparse==1.7
      - crafter==1.8.0
      - cython==0.29.36
      - dash==2.14.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dm-control==1.0.8
      - dm-env==1.6
      - docker-pycreds==0.4.0
      - einops==0.3.0
      - etils==1.5.2
      - exceptiongroup==1.2.0
      - farama-notifications==0.0.4
      - fasteners==0.19
      - fastjsonschema==2.19.0
      - ffmpeg==1.4
      - flash-attn==2.7.4.post1
      - flask==3.0.0
      - fonttools==4.46.0
      - fsspec==2023.12.2
      - future==1.0.0
      - gdown==4.7.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - glfw==2.10.0
      - google-auth==2.25.2
      - google-auth-oauthlib==1.2.0
      - grpcio==1.60.0
      - gym==0.12.5
      - gymnasium==0.28.1
      - gymnasium-robotics==1.2.2
      - h5py==3.14.0
      - hydra-core==1.1.0
      - hydra-submitit-launcher==1.1.5
      - idna==3.6
      - imageio==2.37.0
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==7.0.0
      - ipython==8.18.1
      - ipywidgets==8.1.1
      - itsdangerous==2.1.2
      - jax-jumpy==1.0.0
      - jinja2==3.1.6
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - jupyter-core==5.5.0
      - jupyterlab-widgets==3.0.9
      - keras==3.11.3
      - kornia==0.7.0
      - labmaze==1.0.6
      - llvmlite==0.41.1
      - markdown==3.5.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.5.0
      - memory-maze==1.0.3
      - ml-dtypes==0.5.3
      - mujoco==2.3.3
      - nbformat==5.7.0
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - ninja==1.13.0
      - numba==0.58.1
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.1.2
      - open3d==0.17.0
      - opencv-contrib-python==4.8.1.78
      - opencv-python==4.7.0.72
      - opensimplex==0.4.5
      - packaging==25.0
      - pandas==2.3.2
      - patchelf==0.17.2.1
      - pettingzoo==1.24.3
      - pillow==11.3.0
      - platformdirs==4.1.0
      - plotly==5.18.0
      - prompt-toolkit==3.0.43
      - protobuf==6.32.0
      - ptyprocess==0.7.0
      - pyasn1==0.5.1
      - pycparser==2.21
      - pygame==2.1.0
      - pyglet==2.1.8
      - pyopengl==3.1.1a1
      - pyopengl-accelerate==3.1.10
      - pyparsing==2.4.7
      - pyquaternion==0.9.9
      - pyyaml==6.0.2
      - referencing==0.32.0
      - requests==2.31.0
      - retrying==1.3.4
      - rich==14.1.0
      - rpds-py==0.13.2
      - rtree==1.1.0
      - ruamel-yaml==0.17.4
      - safety-gymnasium==1.0.0
      - sapien==2.2.1
      - scikit-learn==1.3.2
      - scikit-video==1.1.11
      - scipy==1.8.0
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - setuptools==61.0.0
      - setuptools-scm==9.2.0
      - six==1.17.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - submitit==1.5.1
      - sympy==1.13.1
      - tenacity==8.2.3
      - tensorboard==2.20.0
      - tensordict-nightly==2023.12.14
      - tensorflow==2.20.0
      - tensorflow-io==0.37.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - tomli==2.0.1
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tqdm==4.66.1
      - traitlets==5.14.0
      - transforms3d==0.4.1
      - trimesh==4.0.5
      - triton==3.2.0
      - typing-extensions==4.15.0
      - wandb==0.16.1
      - wcwidth==0.2.12
      - werkzeug==3.0.1
      - wheel==0.38.4
      - widgetsnbextension==4.0.9
      - xmltodict==1.0.0
      - zipp==3.17.0
prefix: /home/general/anaconda3/envs/hrssm_saferl
